title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
github_username: nighthawkcoders
<<<<<<< HEAD
baseurl: "/student"
# remote_theme: pages-themes/midnight@v0.2.0
=======
baseurl: "/solid-octo-goggles"
remote_theme: pages-themes/midnight@v0.2.0
>>>>>>> 202d71d61ff41f172d23dca989fa3924d210abcd
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0

plugins:
- jekyll-remote-theme
future: true
